name: md5-CI-build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: windows-latest
    steps:
      - name: disable auto crlf
        uses: steve02081504/disable-autocrlf@v1
      - name: checkout
        uses: actions/checkout@v2
      - name: updates build
        uses: Taromati2/ukagaka-mirror-md5-CI-build@v1
        with:
          no-push: true
          build-mode: other
      - name: git push
        # commit and push all changes at once to avoid error
        run: |
          git config --local user.email "calcium629@gmail.com"
          git config --local user.name "apxxxxxxe"
          git add .
          git commit -m "update md5" -a
          git pull
          git push origin $(git symbolic-ref --short HEAD)
